spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxxxxx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: xxxxxxxxx
    password: xxxxxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  type-aliases-package: com.cqupt.xuetu.entity          # 所有实体类所在包路径
  mapper-locations: classpath:mybatis/mappers/*.xml      # mapper映射文件

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置log4j

server:
  port: 8081 # 服务端口号

alipay:
  # appId
  appId: 
  # 应用私钥
  appPrivateKey: 
  # 支付宝公钥
  alipayPublicKey: 
  # 支付成功回调地址
  notifyUrl: 
